version: "2"

services:

  publish:
    image: publish_local
    ports:
      - "8061:80"
    depends_on:
      - mongo
    restart: always
    volumes:
      - web:/var/www/plantnet-publish/web
    environment:
      PUBLISH_SYMFONY_LOCALE: en
      PUBLISH_SYMFONY_SECRET: get_your_own_secret_string
      PUBLISH_PHP_MEMORY_LIMIT: 2048M
      PUBLISH_MONGO_DATABASE: publish_prod
      PUBLISH_ADMIN_USER: admin
      PUBLISH_ADMIN_PASSWORD: _change_me_
      PUBLISH_ADMIN_EMAIL: admin@_change_me_
      PUBLISH_MAILER_TRANSPORT: smtp
      PUBLISH_MAILER_HOST: 127.0.0.1
      PUBLISH_MAILER_USER: null
      PUBLISH_MAILER_PASSWORD: null
      PUBLISH_MAILER_DISABLE: "true"
      PUBLISH_MAILER_FROM_EMAIL_ADDRESS: support@_change_me_
      PUBLISH_MAILER_FROM_SENDER_NAME: _change_me_

  mongo:
    image: "mongo:3.6.8"
    restart: always
    volumes:
      - /opt/plantnet-publish/db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8062:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: _change_me_

volumes:
  web:
