imports:
    - { resource: config.yml }

framework:
    router: { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false
# intercept redirection ici alain

monolog:
    handlers:
        main:
            type: stream
            path: %kernel.logs_dir%/%kernel.environment%.log
            level: error
        firephp:
            type: firephp
            level: info

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com
