plantnet_file_manager:
    resource: "@PlantnetFileManagerBundle/Resources/config/routing.yml"
    prefix: /admin/

PlantnetDataBundle:
    resource: "@PlantnetDataBundle/Controller/"
    type: annotation
    prefix: /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /admin/

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /admin/profile

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /admin/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /admin/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /admin/resetting

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#plantnet_securityrest:
#    resource: Plantnet\UserBundle\Controller\WsseSecurityController
#    type: rest

#plantnet_userrest:
#    resource: "@PlantnetUserBundle/Resources/config/routing.yml"
#    type: rest
#    prefix: /api

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
