<?php

namespace Plantnet\DataBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * DatabaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatabaseRepository extends DocumentRepository
{
}